/**
 * Example Newcomers Club Build Profile
 *
 * Auto-generated by generate-certification.ts
 */

import { BuildProfile } from './config-schema';

export const ENC_AUTO_TAG_RULES = [
  {
    "type": "name-prefix",
    "pattern": "Hiking:",
    "tag": "committee:hiking"
  },
  {
    "type": "name-prefix",
    "pattern": "Social:",
    "tag": "committee:social"
  },
  {
    "type": "name-prefix",
    "pattern": "Book Club:",
    "tag": "committee:book-club"
  },
  {
    "type": "name-prefix",
    "pattern": "Games:",
    "tag": "committee:games"
  }
];

export const ENC_PROFILE: BuildProfile = {
  name: 'ENC',
  description: 'Example Newcomers Club',
  config: {
    "waAccountId": "123456",
    "headerTitle": "ENC Events",
    "primaryColor": "#1a5f7a",
    "accentColor": "#ff9800",
    "autoTagRules": [
        {
            "type": "name-prefix",
            "pattern": "Hiking:",
            "tag": "committee:hiking"
        },
        {
            "type": "name-prefix",
            "pattern": "Social:",
            "tag": "committee:social"
        },
        {
            "type": "name-prefix",
            "pattern": "Book Club:",
            "tag": "committee:book-club"
        },
        {
            "type": "name-prefix",
            "pattern": "Games:",
            "tag": "committee:games"
        }
    ],
    "quickFilters": {
        "weekend": true,
        "openings": true,
        "afterhours": true,
        "free": false,
        "public": true
    },
    "dropdownFilters": {
        "committee": true,
        "activity": true,
        "price": true,
        "eventType": true,
        "recurring": true,
        "venue": true,
        "tags": true
    },
    "publicConfig": {
        "showMyEvents": false,
        "quickFilters": {
            "public": false
        }
    },
    "memberConfig": {
        "showMyEvents": true
    }
},
  expectedBehaviors: [
    {
      description: 'WA Account ID is set to ENC (123456)',
      test: (config) => config.waAccountId === '123456',
    },
    {
      description: 'Has 4 auto-tag rules',
      test: (config) => config.autoTagRules.length === 4,
    },
  ],
  sampleEventTitles: [
    'Hiking: Sample Event',
    'Social: Sample Event',
    'Book Club: Sample Event',
    'Games: Sample Event',
  ],
};
