/**
 * Example Newcomers Club Build Certification Tests
 *
 * Auto-generated by generate-certification.ts
 * Run with: npm run test:certify:enc
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { applyAutoTags } from '../../widget/src/core';
import { DEFAULT_CONFIG, ClubCalendarConfig } from './config-schema';
import { ENC_PROFILE, ENC_AUTO_TAG_RULES } from './enc-profile';

function mergeConfig(base: ClubCalendarConfig, overrides: Partial<ClubCalendarConfig>): ClubCalendarConfig {
  const result = { ...base };
  for (const key of Object.keys(overrides) as (keyof ClubCalendarConfig)[]) {
    const value = overrides[key];
    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      (result as any)[key] = { ...(result as any)[key], ...value };
    } else if (value !== undefined) {
      (result as any)[key] = value;
    }
  }
  return result;
}

describe('ENC Build Profile Validation', () => {
  let config: ClubCalendarConfig;

  beforeAll(() => {
    config = mergeConfig(DEFAULT_CONFIG, ENC_PROFILE.config);
  });

  it('should have valid profile definition', () => {
    expect(ENC_PROFILE.name).toBe('ENC');
    expect(ENC_PROFILE.config.waAccountId).toBe('123456');
  });

  describe('Expected behaviors', () => {
    for (const behavior of ENC_PROFILE.expectedBehaviors) {
      it(behavior.description, () => {
        expect(behavior.test(config)).toBe(true);
      });
    }
  });
});

describe('ENC Auto-Tag Rules', () => {
  it('should have 4 rules', () => {
    expect(ENC_AUTO_TAG_RULES.length).toBe(4);
  });


  it('rule 1: "Hiking:" → "committee:hiking"', () => {
    const tags = applyAutoTags({ Name: 'Hiking: Test Event' }, ENC_AUTO_TAG_RULES);
    expect(tags).toContain('committee:hiking');
  });

  it('rule 2: "Social:" → "committee:social"', () => {
    const tags = applyAutoTags({ Name: 'Social: Test Event' }, ENC_AUTO_TAG_RULES);
    expect(tags).toContain('committee:social');
  });

  it('rule 3: "Book Club:" → "committee:book-club"', () => {
    const tags = applyAutoTags({ Name: 'Book Club: Test Event' }, ENC_AUTO_TAG_RULES);
    expect(tags).toContain('committee:book-club');
  });

  it('rule 4: "Games:" → "committee:games"', () => {
    const tags = applyAutoTags({ Name: 'Games: Test Event' }, ENC_AUTO_TAG_RULES);
    expect(tags).toContain('committee:games');
  });

});

describe('ENC Certification Summary', () => {
  it('should report certification stats', () => {
    console.log('\n═══════════════════════════════════════════════════════════════');
    console.log('ENC BUILD CERTIFICATION SUMMARY');
    console.log('═══════════════════════════════════════════════════════════════');
    console.log(`Build Profile: ${ENC_PROFILE.name}`);
    console.log(`WA Account ID: ${ENC_PROFILE.config.waAccountId}`);
    console.log(`Auto-Tag Rules: ${ENC_AUTO_TAG_RULES.length}`);
    console.log('═══════════════════════════════════════════════════════════════\n');
  });
});
